# variables:
  # SERVICE_NAME: go-api # SERVICE_NAME: area-china-api-pangpang-common # serviceName + namespace
  # FOLDERNAME: ""  # for example: nomni/
  # GOBUILD_ENV: ""
  # GOTEST_ENV: "-e JWT_SECRET=1234"
  # RTC_ENV: " --docker-no-login --env production "
variables:
  SERVICE_NAME: go-api
include: 
  - project: 'open/gitlab-ci'
    file: '/templates/go.gitlab-ci.yml'