database:
  driver: mysql
  connection: root:1234@tcp(test-mysql:3306)/fruit?charset=utf8&parseTime=True&loc=UTC
  name: fruit
  logger:
    kafka:
      brokers:
        - test-kafka:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - test-kafka:9092
    topic: behaviorlog
eventBroker:
  kafka:
    brokers:
      - test-kafka:9092
    topic: fruit
serviceName: go-api
httpPort: 8080