database:
  driver: mysql
  connection: xxx:xxx@tcp(10.30.8.55:3306)/fruit?charset=utf8&parseTime=True&loc=UTC
  logger:
    kafka:
      brokers:
        - 10.30.8.55:9092
      topic: sqllog
eventBroker:
  kafka:
    brokers:
      - 10.30.8.55:9092
    topic: fruit
behaviorLog:
  kafka:
    brokers:
      - 10.30.8.55:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080