database:
  driver: mysql
  connection: root:1234@tcp(10.30.8.55:3308)/fruit?charset=utf8&parseTime=True&loc=Local
  name: fruit
  logger:
    kafka:
      brokers:
        - 10.30.8.55:9092
      topic: sqllog
eventBroker:
  kafka:
    brokers:
      - 10.30.8.55:9092
    topic: fruit
behaviorLog:
  kafka:
    brokers:
      - 10.30.8.55:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080