database:
  driver: mysql
  connection: root:1234@tcp(10.202.101.230:3308)/fruit?charset=utf8&parseTime=True&loc=UTC
  logger:
    kafka:
      brokers:
        - 10.202.101.230:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 10.202.101.230:9092
    topic: behaviorlog
eventBroker:
  kafka:
    brokers:
      - 10.202.101.230:9092
    topic: fruit
serviceName: go-api
httpPort: 8080